#!/bin/bash

# A command that takes to regular expressions.
# Arg1: A regex representing the source files/directories.
# Arg2: A regex representing the destination files/directories.
# 
# Both Arg1 and Arg2 are paths to source/destination respectively.

# Modes:
# -r: Match the destination regex to the source file, rather than the cwd.
# Not sure how that's going to work quite yet.
# Something along the lines of:
#	cpx -r "^(.)$ "dest/\test_\1"
# Taking:
#	a b c dest/
# Produces:
#	a b c dest/test_a dest/test_b dest/test_c

mode_r=false;

if [ -n "$( echo $@ | grep "\-r" )" ]
then
	echo "In -r mode."
	mode_r=true
fi

echo "Pass 1"
sources=( $( ls | egrep -o "$1" ) )
echo "Pass 2"
if [ $mode_r = true ]
then
	echo "Pass 3a"
	destinations=( $( echo ${sources[@]} | sed "s/$1/$2/" ) )
else
	destinations=( $( ls | egrep -o "$2" ) )
	echo "Pass 3b: $destinations"
fi 
echo "$2"
echo "Pass 4: ${destinations[@]}"
for d in ${destinations[@]}
do
	echo "$d"
	cp "${sources[@]}" "$d" || exit
done
echo "Done"
