#!/bin/bash

# Iterates through the directories in your cwd, applying the given command.

if [ -n "$( echo $1 | egrep "^\-[0-9]$" )" ]; then
	# Level supplied.
	l=$1
	l=${l:1}
	command=$2
else
	# Level not supplied. Assumes 1.
	l=1
	command=$1
fi

echo "Command: $command"

let "l-=1"

for i in */; do
	# Go over all directories in the cwd.

	cd $i
	echo "Currently in $( pwd )"
	
	# If we're still not on level 0
	if [ $l -gt 0 ]; then
		# Repeat the foreach command.
		echo "Going down one level:"
		( $0 -$l "$command" | sed "s/^\(.\)/     \1/" ) || ( code=$?; cd ..; exit $code)
	else
		# We're on the right level. Run the command.
		( echo "$command" | bash 2>&1 | sed "s/^\(.\)/     \1/" ) || ( code=$?; cd ..; exit $code)
	fi
	cd ..
done
