#!/bin/bash

# Iterates through the directories in your cwd, applying the given command.

if [ -n "$( echo $1 | egrep "\-[0-9]" )" ]; then
	# Level supplied.
	l=$1
	l=${l:1}
	command=$2
else
	# Level not supplied. Assumes 1.
	l=1
	command=$1
fi

echo "Command: $command"

let "l-=1"

for i in */; do
	# Go over all directories in the cwd.

	cd $i
	echo "Currently in $( pwd )"
	
	# If we're still not on level 0
	if [ $l -gt 0 ]; then
		# Repeat the foreach command.
		echo "Wrong floor. Going down one."
		$0 -$l "$command" || ( cd ..; exit )
	else
		# We're on the right level. Run the command.
		echo "$command" | bash || ( cd ..; exit )
	fi
	cd ..
done
